---
title: "Col Ext by Region"
output: html_notebook
---
```{r setup}

library(data.table)
library(ggplot2)
library(lme4)
library(dplyr)

load("~/Documents/grad school/Rutgers/LabWork/Colonization_Extinction/spp_master_ztemp.Rdata")

```
First, let's get some regional statistics
```{r regional stats}
#count colonizations by region
col <- spp_master_ztemp %>%
  group_by(reg) %>%
  summarise(sum(col))

#count extinctions by region
ext <- spp_master_ztemp %>%
  group_by(reg) %>%
  summarise(sum(now_ext))

#count observations by region
count <- spp_master_ztemp %>%
  group_by(reg) %>%
  summarise(n())

#first year
year.first <- spp_master_ztemp %>%
  group_by(reg) %>%
  summarise(min(year))
#last year
year.last <- spp_master_ztemp %>%
  group_by(reg) %>%
  summarise(max(year))

region_summaries <- cbind(count, col[,2], ext[,2], year.first[,2], year.last[,2])
colnames(region_summaries) <- c("reg", "n", "n.col", "n.ext", "year.first","year.last")
```
Now we'll visualize regions in a plot
```{r region plot}
#manipulate data
region_summaries.m <- melt(region_summaries[,1:4], id.vars = "reg")

ggplot(aes(x=reg, y = value, fill = variable), data = region_summaries.m) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Region", y = "Counts")

```

Now, let's do the same process as we did in 04_24_19_Temp_link_traits_fish BUT region specific
```{r surface colonization comparison by region}
#playing with year as factor
spp_master_ztemp[,year_factor := as.factor(year)]

surface_variables <- colnames(spp_master_ztemp[,45:168])
  
#regions

#ai (17, 50, 51, 75 fail to converge)
surface_colonization_model_comparison_ai <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_ai[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_ai[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "ai"])
    surface_colonization_model_comparison_ai[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_ai[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_ai[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_ai[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }
  #add column for those that didn't converge
  surface_colonization_model_comparison_ai$converge <- T
  surface_colonization_model_comparison_ai$converge[c(17, 50, 51, 75)] <- F
  
  #add column to designate region 
  surface_colonization_model_comparison_ai$reg <- "ai"
#ebs (14 did not converge)

surface_colonization_model_comparison_ebs <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_ebs[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_ebs[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "ebs"])
    surface_colonization_model_comparison_ebs[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_ebs[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_ebs[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_ebs[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }
  #add column for those that didn't converge
  surface_colonization_model_comparison_ebs$converge <- T
  surface_colonization_model_comparison_ebs$converge[c(14)] <- F
  
  #add column to designate region 
  surface_colonization_model_comparison_ebs$reg <- "ebs"
  
#gmex (1:30 fail to converge)

surface_colonization_model_comparison_gmex <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_gmex[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_gmex[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "gmex"])
    mod1 <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "gmex"])
    surface_colonization_model_comparison_gmex[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_gmex[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_gmex[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_gmex[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }
  #add column for those that didn't converge
  surface_colonization_model_comparison_gmex$converge <- T
  surface_colonization_model_comparison_gmex$converge[c(1:30)] <- F
  
  #add column to designate region 
  surface_colonization_model_comparison_gmex$reg <- "gmex"

#goa

surface_colonization_model_comparison_goa <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_goa[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_goa[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "goa"])
    surface_colonization_model_comparison_goa[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_goa[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_goa[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_goa[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }
  #add column for those that didn't converge
  surface_colonization_model_comparison_goa$converge <- T
  
  #add column to designate region 
  surface_colonization_model_comparison_goa$reg <- "goa"

#neus (1, 6:8, 12, 15, 17, 21, 23, 33, 36:40 failed to converge)

surface_colonization_model_comparison_neus <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_neus[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_neus[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "neus"])
    surface_colonization_model_comparison_neus[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_neus[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_neus[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_neus[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }
#add column for those that didn't converge
surface_colonization_model_comparison_neus$converge <- T
surface_colonization_model_comparison_neus$converge[c(1, 6:8, 12, 15, 17, 21, 23, 22, 36:40)] <- F

#add column to designate region 
  surface_colonization_model_comparison_neus$reg <- "neus"

#newf (112 failed to converge)

surface_colonization_model_comparison_newf <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_newf[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_newf[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "newf"])
    surface_colonization_model_comparison_newf[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_newf[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_newf[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_newf[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }

#add column for those that didn't converge
surface_colonization_model_comparison_newf$converge <- T
surface_colonization_model_comparison_newf$converge[c(112)] <- F

#add column to designate region 
  surface_colonization_model_comparison_newf$reg <- "newf"


#shelf (37:39 didn't converge)

surface_colonization_model_comparison_shelf <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_shelf[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_shelf[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "shelf"])
    surface_colonization_model_comparison_shelf[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_shelf[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_shelf[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_shelf[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }

#add column for those that didn't converge
surface_colonization_model_comparison_shelf$converge <- T
surface_colonization_model_comparison_shelf$converge[c(37:39)] <- F

#add column to designate region 
  surface_colonization_model_comparison_shelf$reg <- "shelf"


#sa (all are singularities??)

surface_colonization_model_comparison_sa <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_sa[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_sa[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "sa"])
    surface_colonization_model_comparison_sa[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_sa[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_sa[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_sa[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }

#add column for those that didn't converge
surface_colonization_model_comparison_sa$converge <- T
surface_colonization_model_comparison_sa$converge[c(1:124)] <- F

#add column to designate region 
  surface_colonization_model_comparison_sa$reg <- "sa"


#wctri (16, 27, 37, 38, 51, 52, 60, 61, 64, 65, 68, 70, 74, 75, 97, 99, 102, 104, 112 failed to converge)

surface_colonization_model_comparison_wctri <- as.data.table(matrix(nrow = length(surface_variables)))
surface_colonization_model_comparison_wctri[, variable:=as.factor(V1)][, coef:=as.numeric(V1)][, p_value:=as.numeric(V1)][, AICc:=as.numeric(V1)]
surface_colonization_model_comparison_wctri[, V1 := NULL]
  
  for (i in 1:length(surface_variables)){
    mod <- glmer(col ~ get(surface_variables[i]) + (1|year_factor), family = binomial, data = spp_master_ztemp[reg == "wctri"])
    surface_colonization_model_comparison_wctri[i,variable := surface_variables[i]]
    surface_colonization_model_comparison_wctri[i,coef := coef(summary(mod))[,"Estimate"][2]]
    surface_colonization_model_comparison_wctri[i,p_value := coef(summary(mod))[,"Pr(>|z|)"][2]]
    surface_colonization_model_comparison_wctri[i,AICc := AICc(mod)]
    
    print(paste(i, length(surface_variables), sep = "/"))
      
  }

#add column for those that didn't converge
surface_colonization_model_comparison_wctri$converge <- T
surface_colonization_model_comparison_wctri$converge[c(16, 27, 37, 38, 51, 52, 60, 61, 64, 65, 68, 70, 74, 75, 97, 99, 102, 104, 112)] <- F

#add column to designate region 
  surface_colonization_model_comparison_wctri$reg <- "wctri"

```

Now, I'll merge all surface colonization models
```{r merge surface colonization models}
surface_colonization_model_comparison_byregion <- rbind(surface_colonization_model_comparison_ai, surface_colonization_model_comparison_ebs, surface_colonization_model_comparison_gmex, surface_colonization_model_comparison_goa, surface_colonization_model_comparison_neus, surface_colonization_model_comparison_newf, surface_colonization_model_comparison_sa, surface_colonization_model_comparison_shelf, surface_colonization_model_comparison_wctri)
```

Best few models per region

```{r best models per region}
surface_colonization_model_comparison_byregion %>%
  filter(converge == TRUE, !grepl("mean", variable)) %>% #ignoring mean for now, and get rid of those that didn't converge
  group_by(reg) %>% #group by region
  arrange(AICc) %>% #arrange by AICc
  top_n(-5, AICc) #take 5 best models (lowest AICc)
  
```

