---
title: "Map of Sites"
output: html_notebook
---

```{r setup}
library(data.table)
library(mapdata)
library(maps)
library(plyr)
library(ggplot2)

load("hauls_catch_Dec2017 1.RData")


```

```{r extract unique GPS points}
hauls <- data.table(hauls)

hauls2 <- hauls[year <= 2000 & year >= 1996]
#all regions sampled 1996-2000

gpspointsonly <- hauls2[, .(region, lat, lon)]
gpspointsonly_quarterdegreeround <- copy(gpspointsonly) #in order to look at all points
gpspointsonly[, lat := round_any(lat, 0.5)][, lon := round_any(lon, 0.5)][, region := as.factor(region)]
gpspointsonly_quarterdegreeround[, lat := round_any(lat, 0.25)][, lon := round_any(lon, 0.25)][, region := as.factor(region)]
gpspointsonly <- unique(gpspointsonly[,.(region, lat, lon)])
gpspointsonly_quarterdegreeround <- unique(gpspointsonly_quarterdegreeround[,.(region, lat, lon)])

gpspointsonly <- gpspointsonly[region != "DFO_SoGulf" & region != "NWFSC_WCAnn" & region != "VIMS_NEAMAP"] #taking away regions we don't look at
gpspointsonly_quarterdegreeround <- gpspointsonly_quarterdegreeround[region != "DFO_SoGulf" & region != "NWFSC_WCAnn" & region != "VIMS_NEAMAP"] #taking away regions we don't look at


#rename factors
key <- data.table(region = as.factor(levels(gpspointsonly[,region])), Regions = c("Aleutian Islands", "Eastern Bering Sea", "Gulf of Alaska", "West Coast Triennial", "Newfoundland", "Scotian Shelf", NA, "Northeast US", "Southeast US", "Gulf of Mexico"))

gpspointsonly <- gpspointsonly[key, on = "region"]
gpspointsonly_quarterdegreeround <- gpspointsonly_quarterdegreeround[key, on = "region"]

save(gpspointsonly, gpspointsonly_quarterdegreeround, file = "trawl_coordinates_1996-2000.RData")

```

```{r set up map}
world <- data.table(map_data('world'))

north_america <- world[long >= -250 & long <= -30 & lat >= 20 & lat <= 80]

NAmap <- ggplot() + geom_polygon(data = north_america, 
                                 aes(x=long, y = lat, group = group), 
                                 fill = "white", 
                                 color="black") +
    coord_fixed(xlim = c(-200, -40),  ylim = c(25, 65), ratio = 1.3)

```
Add points and polygons
```{r add points}
#color palette
library(wesanderson)
pal <- wes_palette("GrandBudapest1", 9, type = "continuous")


(NAplot_polygons <- ggplot() + geom_polygon(data = north_america, 
                                 aes(x=long, y = lat, group = group), 
                                 fill = "white", 
                                 color="black", size = 0.02) +
            coord_fixed(xlim = c(-190, -40),  ylim = c(25, 65), ratio = 1.3) + 
            geom_point(data = gpspointsonly[!is.na(Regions)], aes(x=lon, y = lat, color = Regions), size = 0.001) +
            scale_color_manual(values = c(pal[2], pal[4], pal[7], pal[5],pal[6],pal[3],pal[8],pal[9],pal[1])) +
            guides(color = guide_legend(override.aes = list(size = 1))) +
            geom_jitter() +
            theme_bw() +
            labs(x=paste0("Longitude (", "\u00b0", "E)"), y = paste0("Latitude (", "\u00b0", "N)"))+
            theme(panel.grid = element_blank(), legend.position = "left"))

ggsave(plot = NAplot_polygons, file = "NAplot_polygons.eps")

```

```{r add SEUS points}
NAplot_polygons_SEUS <- ggplot() + geom_polygon(data = north_america, 
                                 aes(x=long, y = lat, group = group), 
                                 fill = "white", 
                                 color="black", size = 0.02) +
            coord_fixed(xlim = c(-82, -70),  ylim = c(27, 36), ratio = 1.3) + 
            geom_point(data = gpspointsonly[!is.na(Regions)], aes(x=lon, y = lat, color = Regions), size = 1) +
            geom_point(data = latlon_seus, aes(x=lon, y = lat), color = "black") +
            guides(color = guide_legend(override.aes = list(size = 1))) +
            geom_jitter() +
            theme_bw() +
            labs(x=paste0("Longitude (", "\u00b0", "E)"), y = paste0("Latitude (", "\u00b0", "N)"))+
            theme(panel.grid = element_blank())

NAplot_polygons_SEUS

ggsave(NAplot_polygons_SEUS, file = "NAplot_polygons_SEUS.png")
```


