---
title: "Plotting Best Models"
output: html_notebook
---
```{r setup}
library(dplyr)
library(ggplot2)
library(data.table)
library(lme4)
library(ggeffects)

#data
load("extinction_models_with_likelihoods.Rdata")
load("colonization_models_with_likelihoods.Rdata")
load("extinction_models_traits_with_likelihoods.Rdata")
load("colonization_models_traits_with_likelihoods.Rdata")
load("spp_master_ztemp.Rdata")
load("spp_master_ztemp.traits.Rdata")
```

##Colonization
Best Model: max_sbt_temp_change_abs
```{r colonization models}
#our model
mod_col <- glmer(col ~ max_sbt_temp_change_abs + (1|reg) + (1|year), family = binomial, data = spp_master_ztemp)
summary(mod_col)
#what x values do we need to predict for?
range(spp_master_ztemp$max_sbt_temp_change_abs)

#seq x values to predict for
xtemp <- seq(0, 6.5, 0.01)

#predicted values
ggpredict(mod_col, "max_sbt_temp_change_abs")



#plot
#marginal effects
me_col <- ggpredict(mod_col, "max_sbt_temp_change_abs")
plot(me_col)
ggsave(path = "plots/marginal_effects", file= "predicted_probs_col_temponly.jpg")
ggplot(me_col, aes( x = x, y = predicted)) +
  stat_smooth(method = "loess", se = T, fullrange =T) +
  labs(x = "Absolute Change in Max Bottom Temperature", y = "Probability of Colonization",title = "Predicted Probabilities of Colonization") +
  theme_classic()

#plot random effects
re_reg <- ggpredict(mod_col,"reg", type = "re")
plot(re_reg)

re_year <- ggpredict(mod_col,"year", type = "re")
plot(re_year)

```

##Extinction
Best model: seas_sbt_temp_change_abs_lag9
```{r ext }
#our model
mod_ext <- glmer(now_ext ~ seas_sbt_temp_change_abs_lag9 + (1|reg) + (1|year), family = binomial, data = spp_master_ztemp)
summary(mod_ext)
#what x values do we need to predict for?
range(spp_master_ztemp$seas_sbt_temp_change_abs_lag9)

#seq x values to predict for
xtemp_ext <- seq(0, 5, 0.01)

#predicted values
ggpredict(mod_ext, "seas_sbt_temp_change_abs_lag9")

#plot
#marginal effects
me_ext <- ggpredict(mod_ext, "seas_sbt_temp_change_abs_lag9")
plot(me_ext)
ggsave(path = "plots/marginal_effects", file= "predicted_probs_ext_temponly.jpg")
ggplot(me_ext, aes( x = x, y = predicted)) +
  stat_smooth(method = "loess", se = T, fullrange =T) +
  labs(x = "Absolute Change in Bottom Temperature Seasonality Lagged 9 Years", y = "Probability of Extinction",title = "Predicted Probabilities of Extinction") +
  ylim(c(0,0.1)) +
  theme_classic()
  

#plot random effects
re_reg_ext <- ggpredict(mod_ext,"reg", type = "re")
plot(re_reg_ext)

re_year_ext <- ggpredict(mod_ext,"year", type = "re")
plot(re_year_ext)
```

##Colonization with Traits
Best model: seas_sbt_temp_change_abs_lag4 * age.max
```{r col with traits}
#prepping data table
  spp_master_ztemp.traits.nonas <- na.omit(spp_master_ztemp.traits, cols=c("age.max", "age.maturity", "tl")) #gets rid of any rows missing any of these trait data values
  spp_master_ztemp.traits.nonas.nomean <- spp_master_ztemp.traits.nonas[, grep("mean*", colnames(spp_master_ztemp.traits.nonas)):=NULL] #get rid of columns with mean temp variables
  colonization.reduced <- spp_master_ztemp.traits.nonas.nomean[,c(1, 3, 6, 45:230, 239, 246, 251)]#reduces to columns we need
  colonization.reduced[,year := as.factor(year)]

#model
mod_col_trait <- glmer(col ~ seas_sbt_temp_change_abs_lag4 * age.max + (1|reg) + (1|year), family = "binomial", data = colonization.reduced)

#plot marginal effects of interactions
dat <- ggpredict(mod_col_trait, c("seas_sbt_temp_change_abs_lag4 [all]", "age.max [1,50,100,200]"))

ggplot(dat, aes(x=x, y = predicted, colour = group)) +
  stat_smooth(method = "loess", se = F, fullrange =T) +
  labs(colour="Maximum Age Values", x = "Absolute Change in Bottom Temperature Seasonality Lagged 4 Years", y = "Probability of Colonization",title = "Predicted Probabilities of Colonization") +
  scale_y_continuous(breaks=c(0, 0.5, 1)) +
  theme_classic()

ggsave(path = "plots/marginal_effects", file = "predicted_probs_col_maxage.jpg")

```

##Extinction with Traits
Best Model: max_sbt_temp_change_abs_lag2 * age.max + age.maturity
```{r ext with traits}
#prepping data table
extinction.reduced <- spp_master_ztemp.traits.nonas.nomean[,c(1, 3, 9, 45:230, 239, 246, 251)]
  extinction.reduced[,year := as.factor(year)]

#model
mod_ext_trait <- glmer(now_ext ~ max_sbt_temp_change_abs_lag2 * age.max + age.maturity + (1|reg) + (1|year), family = "binomial", data = extinction.reduced)

#plot marginal effects of interactions
dat <- ggpredict(mod_ext_trait, c("max_sbt_temp_change_abs_lag2 [all]", "age.max [1,50,100,200]"))

ggplot(dat, aes(x=x, y = predicted, colour = group)) +
  stat_smooth(method = "loess", se = F, fullrange =T) +
  labs(colour= "Maximum Age Values", x = "Absolute Change in Max Bottom Temperature 2 Years Ago", y = "Extinction Probability",title = "Predicted Probabilities of Extinction") +
  scale_y_continuous(breaks=c(0, 0.5, 1)) +
  theme_classic()

ggsave(path = "plots/marginal_effects", file = "predicted_probs_ext_maxage.jpg")

#also, let's take a look at age at maturity
dat2 <- ggpredict(mod_ext_trait, c("max_sbt_temp_change_abs_lag2 [all]", "age.maturity [0.5, 20, 50, 80]"))
plot(dat2)
  #as change in temperature increases, the probability of going extinct increases MOST if you mature early and LEAST if you mature late
summary(mod_ext_trait)
```


