---
title: "Regional Richness Temp Change Figure"
output: html_notebook
---

```{r setup}
library(dplyr)
library(data.table)
library(ggplot2)

load("spp_master_ztemp_scaled.Rdata")
```


##Malin's way: average trends over all years
```{r functions}

trend <- function(y, x){ #function to extract coefficient
	return(coef(lm(y ~ x))[2])
}

scale <- function(x){ # function to scale by (ni-nmean)/sdn
	return((x-mean(x))/sd(x))
}

```

Add trends and new variables
```{r trends and new var}
#raw
spp_master_richness[,bt_trend_max_raw:=mean(max_sbt_temp), by=reg]
spp_master_richness[,bt_trend_min_raw:=mean(min_sbt_temp), by=reg]
spp_master_richness[,bt_trend_mean_raw:=mean(mean_sbt_temp), by=reg]
spp_master_richness[,bt_trend_seas_raw:=mean(seas_sbt_temp), by = reg]

spp_master_richness[,bt_trend_max_raw_sc:=scale(bt_trend_max_raw)] 
spp_master_richness[,bt_trend_min_raw_sc:=scale(bt_trend_min_raw)] 
spp_master_richness[,bt_trend_mean_raw_sc:=scale(bt_trend_mean_raw)]

#change
spp_master_richness[,bt_trend_max_change:=trend(max_sbt_temp_change,year), by=reg]
spp_master_richness[,bt_trend_min_change:=trend(min_sbt_temp_change,year), by=reg]
spp_master_richness[,bt_trend_mean_change:=trend(mean_sbt_temp_change,year), by=reg]
spp_master_richness[,bt_trend_seas_change:=trend(seas_sbt_temp_change,year), by=reg]

spp_master_richness[,bt_trend_max_change_sc:=scale(bt_trend_max_change)] 
spp_master_richness[,bt_trend_min_change_sc:=scale(bt_trend_min_change)] 
spp_master_richness[,bt_trend_mean_change_sc:=scale(bt_trend_mean_change)]

#abs change
spp_master_richness[,bt_trend_max_abs_change:=abs(bt_trend_max_change), by=reg]#max bottom temp per year
spp_master_richness[,bt_trend_min_abs_change:=abs(bt_trend_min_change), by=reg]#min bottom temp change per year
spp_master_richness[,bt_trend_mean_abs_change:=abs(bt_trend_mean_change), by=reg]#mean bottom temp change per year
spp_master_richness[,bt_trend_seas_abs_change:=abs(bt_trend_seas_change), by=reg]#mean bottom temp change per year

spp_master_richness[,bt_trend_max_abs_change_sc:=scale(bt_trend_max_abs_change)] #scaled max bottom temp change per year
spp_master_richness[,bt_trend_min_abs_change_sc:=scale(bt_trend_min_abs_change)] #scaled min bottom temp change per year
spp_master_richness[,bt_trend_mean_abs_change_sc:=scale(bt_trend_mean_abs_change)] #scaled mean bottom temp change per year





spp_master_richness[,year_sc:=scale(year)] #scaled year

```
It looks like Malin gets the trend, and THEN scales, so I will try that
```{r}

```

Summary data
```{r summary data}
# create summary data
trends_zoe <- spp_master_richness[,.(rich=trend(richness, year), #calculate trend in richness per year and trend in annual temp per year
                                 bt_trend_max_abs_change = mean(bt_trend_max_abs_change) , 
                                 bt_trend_min_abs_change = mean(bt_trend_min_abs_change) , 
                                 bt_trend_mean_abs_change = mean(bt_trend_mean_abs_change),
                                 bt_trend_seas_abs_change = mean(bt_trend_seas_abs_change),
                                 bt_trend_max_change = mean(bt_trend_max_change) , 
                                 bt_trend_min_change = mean(bt_trend_min_change) , 
                                 bt_trend_mean_change = mean(bt_trend_mean_change) ,
                                 bt_trend_seas_change = mean(bt_trend_seas_change),
                                 bt_trend_max_raw = mean(bt_trend_max_raw) ,
                                 bt_trend_min_raw = mean(bt_trend_min_raw) ,
                                 bt_trend_mean_raw = mean(bt_trend_mean_raw),
                                 bt_trend_seas_raw = mean(bt_trend_seas_raw)),  by=reg] 


trends_zoe[,bt_trend_max_abs_change_scaled := scale(bt_trend_max_abs_change)][,
                                 bt_trend_min_abs_change_scaled := scale(bt_trend_min_abs_change)][,
                                 bt_trend_mean_abs_change_scaled := scale(bt_trend_mean_abs_change)][,
                                 bt_trend_seas_abs_change_scaled := scale(bt_trend_seas_abs_change)][,
                                 bt_trend_max_change_scaled := scale(bt_trend_max_change)][,
                                 bt_trend_min_change_scaled := scale(bt_trend_min_change)][,
                                 bt_trend_mean_change_scaled := scale(bt_trend_mean_change)][,
                                 bt_trend_seas_change_scaled := scale(bt_trend_seas_change)][,
                                 bt_trend_max_raw_scaled := scale(bt_trend_max_raw)][,
                                 bt_trend_min_raw_scaled := scale(bt_trend_min_raw)][,
                                 bt_trend_mean_raw_scaled := scale(bt_trend_mean_raw)][,
                                 bt_trend_seas_raw_scaled := scale(bt_trend_seas_raw)]

setkey(trends_zoe, reg)
```

Plot Max Change and Abs
```{r plot max}
#Raw

#raw mods for abline
raw_max_mod <- lm(rich~bt_trend_max_raw, data = trends_zoe)
summary(raw_max_mod)$r.squared
anova(raw_max_mod)$'Pr(>F)'[1]
# R^2 =  0.1420429
#p value = 0.3173871


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_max_raw, y = rich, col = reg), size = 4) +
  geom_abline(intercept = raw_max_mod$coefficients[[1]], slope = raw_max_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_min_raw, y = rich), col = "blue") +
  #geom_abline(intercept = raw_min_mod$coefficients[[1]], slope = raw_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average\nMaximum Temperature (°C)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_max_raw.jpeg")
  
  
#Change


#change mods for abline
change_max_mod <- lm(rich~bt_trend_max_change, data = trends_zoe)
summary(change_max_mod)$r.squared
anova(change_max_mod)$'Pr(>F)'[1]
# R^2 = 0.1677293
#p value = 0.2736701



ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_max_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = change_max_mod$coefficients[[1]], slope = change_max_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_max_change, y = rich), col = "blue") +
  #geom_abline(intercept = change_min_mod$coefficients[[1]], slope = change_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Change in \nMax Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_max_change.jpeg")

#Absolute Change
#abs change mods for abline
abs_change_max_mod <- lm(rich~bt_trend_max_abs_change, data = trends_zoe)
summary(abs_change_max_mod)$r.squared
anova(abs_change_max_mod)$'Pr(>F)'[1]
# R^2 = 0.1750758
#p value = 0.2623728


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_max_abs_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = abs_change_max_mod$coefficients[[1]], slope = abs_change_max_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_max_abs_change, y = rich), col = "blue") +
  #geom_abline(intercept = abs_change_min_mod$coefficients[[1]], slope = abs_change_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Absolute Change\nin Max Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_max_change_abs.jpeg")
```

Plot Min for Change and Abs
```{r min plots}
#Raw

#raw mods for abline
raw_min_mod <- lm(rich~bt_trend_min_raw, data = trends_zoe)
summary(raw_min_mod)$r.squared
anova(raw_min_mod)$'Pr(>F)'[1]
# R^2 = 0.05175603
#p value = 0.5560681



ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_min_raw, y = rich, col = reg), size = 4) +
  geom_abline(intercept = raw_min_mod$coefficients[[1]], slope = raw_min_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_min_raw, y = rich), col = "blue") +
  #geom_abline(intercept = raw_min_mod$coefficients[[1]], slope = raw_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average\nMinimum Temperature (°C)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_min_raw.jpeg")
  
  
#Change


#change mods for abline
change_min_mod <- lm(rich~bt_trend_min_change, data = trends_zoe)
summary(change_min_mod)$r.squared
anova(change_min_mod)$'Pr(>F)'[1]
# R squared: 0.525328
# p value: 0.02716705



ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_min_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = change_min_mod$coefficients[[1]], slope = change_min_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_min_change, y = rich), col = "blue") +
  #geom_abline(intercept = change_min_mod$coefficients[[1]], slope = change_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Change in \nMin Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_min_change.jpeg")

#Absolute Change
#abs change mods for abline
abs_change_min_mod <- lm(rich~bt_trend_min_abs_change, data = trends_zoe)
summary(abs_change_min_mod)$r.squared
anova(abs_change_min_mod)$'Pr(>F)'[1]
#r squared value: 0.2929706
#p value:0.1323295


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_min_abs_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = abs_change_min_mod$coefficients[[1]], slope = abs_change_min_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_min_abs_change, y = rich), col = "blue") +
  #geom_abline(intercept = abs_change_min_mod$coefficients[[1]], slope = abs_change_min_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Absolute Change\nin Min Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_min_change_abs.jpeg")
```


Plot Mean for Change and Abs
```{r mean plots}
#Raw

#raw mods for abline
raw_mean_mod <- lm(rich~bt_trend_mean_raw, data = trends_zoe)
summary(raw_mean_mod)$r.squared
anova(raw_mean_mod)$'Pr(>F)'[1]
# R squared value: 0.1034685
#p value: 0.3986127


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_mean_raw, y = rich, col = reg), size = 4) +
  geom_abline(intercept = raw_mean_mod$coefficients[[1]], slope = raw_mean_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_mean_raw, y = rich), col = "blue") +
  #geom_abline(intercept = raw_mean_mod$coefficients[[1]], slope = raw_mean_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average\nMean Temperature (°C)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_mean_raw.jpeg")
  
  
#Change


#change mods for abline
change_mean_mod <- lm(rich~bt_trend_mean_change, data = trends_zoe)
summary(change_mean_mod)$r.squared
anova(change_mean_mod)$'Pr(>F)'[1]
#R squared: 0.3887231
#p value: 0.07280526



ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_mean_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = change_mean_mod$coefficients[[1]], slope = change_mean_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_mean_change, y = rich), col = "blue") +
  #geom_abline(intercept = change_mean_mod$coefficients[[1]], slope = change_mean_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Change in \nMean Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_mean_change.jpeg")

#Absolute Change

#abs change mods for abline
abs_change_mean_mod <- lm(rich~bt_trend_mean_abs_change_scaled, data = trends_zoe)
summary(abs_change_mean_mod)$r.squared
anova(abs_change_mean_mod)$'Pr(>F)'[1]
#R Squared: 0.1413137
#P value: 0.3187339


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_mean_abs_change_scaled, y = rich, col = reg), size = 4) +
  geom_abline(intercept = abs_change_mean_mod$coefficients[[1]], slope = abs_change_mean_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_mean_abs_change, y = rich), col = "blue") +
  #geom_abline(intercept = abs_change_mean_mod$coefficients[[1]], slope = abs_change_mean_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Absolute Change\nin Mean Temperature (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

trends_zoe[,.(reg, rich, bt_trend_max_change, bt_trend_mean_change_scaled)][order(reg)]

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_mean_change_abs.jpeg")
```


Plot Seasonality for Change and Abs
```{r Seasonality plots}
#Raw

#raw mods for abline
raw_seas_mod <- lm(rich~bt_trend_seas_raw, data = trends_zoe)
summary(raw_seas_mod)$r.squared
anova(raw_seas_mod)$'Pr(>F)'[1]
# R squared value: 0.3593094
#p value: 0.08800772


ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_seas_raw, y = rich, col = reg), size = 4) +
  geom_abline(intercept = raw_seas_mod$coefficients[[1]], slope = raw_seas_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_seas_raw, y = rich), col = "blue") +
  #geom_abline(intercept = raw_seas_mod$coefficients[[1]], slope = raw_seas_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average\nTemperature\nSeasonality (°C)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_seas_raw.jpeg")
  
  
#Change


#change mods for abline
change_seas_mod <- lm(rich~bt_trend_seas_change, data = trends_zoe)
summary(change_seas_mod)$r.squared
anova(change_seas_mod)$'Pr(>F)'[1]
#R squared: 0.000239069
#p value: 0.9685076



ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_seas_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = change_seas_mod$coefficients[[1]], slope = change_seas_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_seas_change, y = rich), col = "blue") +
  #geom_abline(intercept = change_seas_mod$coefficients[[1]], slope = change_seas_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Change in \nTemperature\nSeasonality (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_seas_change.jpeg")

#Absolute Change
#abs change mods for abline
abs_change_seas_mod <- lm(rich~bt_trend_seas_abs_change, data = trends_zoe)
summary(abs_change_seas_mod)$r.squared
anova(abs_change_seas_mod)$'Pr(>F)'[1]
#R Squared: 7.524088e-05
#P value: 0.9823303




ggplot(data = trends_zoe) +
  geom_point(aes(x = bt_trend_seas_abs_change, y = rich, col = reg), size = 4) +
  geom_abline(intercept = abs_change_seas_mod$coefficients[[1]], slope = abs_change_seas_mod$coefficients[[2]], col = "slategrey", linetype = "dashed") +
  #geom_point(aes(x = bt_trend_seas_abs_change, y = rich), col = "blue") +
  #geom_abline(intercept = abs_change_seas_mod$coefficients[[1]], slope = abs_change_seas_mod$coefficients[[2]], col = "blue") +
  labs(x = "Average Absolute Change\nin Temperature\nSeasonality (°C/yr)", y = "Average change\nin richness (spp/yr)") +
  theme_classic() +
  theme(text = element_text(size = 14))

ggsave(width = 4, height = 3.5, units = "in", path = "plots/richness_change", filename = "richness_trend_seas_change_abs.jpeg")
```
Compare Zoe temp patterns to Ryan's temp patterns
```{r temp comparisons}
load("comm_master.RData")
ryan_reduced <- comm_master[,.(reg, year, naive_rich, bt_ann)][,name:="RYAN"]
zoe_reduced <- unique(spp_master_ztemp[, bt_ann_z := mean(mean_sbt_temp), by = .(reg, year)][,name:="ZOE"][,.(reg, year, bt_ann_z)])

setkey(ryan_reduced, reg, year)
setkey(zoe_reduced, reg, year)
merge <- ryan_reduced[zoe_reduced]

ggplot(data = merge, aes(x = year)) +
  geom_point(aes(y = bt_ann), color = "blue") +
  geom_point(aes(y = bt_ann_z), color = "red") +
  facet_wrap(~reg) +
  theme_bw()
```
Zoe's temp
```{r zoe temp plots}
ggplot(data = spp_master_ztemp.traits, aes(x = year, y = mean_sbt_temp)) +
  geom_point() +
  facet_wrap(~reg) +
  theme_bw()

```

Ryan's temp
```{r Ryans temp plots}
ggplot(data = comm_master, aes(x = year, y = bt_ann)) +
  geom_point() +
  facet_wrap(~reg) +
  theme_bw()
```


