---
title: "Script for AIC plots"
output: html_notebook
---

#colonization

Full model no lag, raw temp : 5464.425
Full model no lag, change in temp: 5457.204
**Full model no lag, absolute change in temperature: 5455.992**

Full model no lag, absolute change in temperature: 5455.992 
Full model lag 1, absolute change in temp: 5464.402
Full model lag 2, absolute change in temp: 5464.594
Full model lag 3, absolute change in temp: 5458.516

Full model no lag, absolute change in temperature, 4 var: 5455.992 
Full model no lag, absolute change in temperature, 3 var: 5455.592
Full model no lag, absolute change in tempreature, 2 var: 5456.013 (max and seas)
Full model no lag, absolute change in temperature, 1 var: 5454.826 (seas)

#extinction

Full model no lag, raw temp: 4723.627 (cannot converge)
Full model no lag, change in temp: 4730.664
Full model, no lag, abs change in temp: 4729.008

Full model no lag, absolute change in temperature: 4729.008 
Full model lag 1, absolute change in temp: 4726.895
**Full model lag 2, absolute change in temp: 4724.949**
Full model lag 3, absolute change in temp: 4729.087

Full model 2 lag, absolute change in temperature, 4 var: 5455.992 
Full model 2 lag, absolute change in temperature, 3 var: 4723.089
Full model 2 lag, absolute change in tempreature, 2 var: 4722.440 
Full model 2 lag, absolute change in temperature, 1 var: 4723.129 (max)




