---
title: "Temp Collinearity"
output: html_notebook
---

Looking at collinearity between temperature predictors. 

```{r setup}
library(data.table)
library(ggplot2)
library(reshape2)
library(ggcorrplot)


load("spp_master_ztemp_seus_buoys.Rdata")
load("~/Documents/grad school/Rutgers/Repositories/Col_Ext/spp_master_ztemp_seus_buoy.traits_scaled.RData")
```

Temp variables we need
```{r narrow down to temp variables that we need}
#columns to keep for collinearity matrix
variable_names_reduced <- colnames(spp_master_ztemp_seus_buoy)[grepl("s.t", colnames(spp_master_ztemp_seus_buoy),)]
variable_names_reduced2 <- variable_names_reduced[!grepl("mean|lag", variable_names_reduced)]

#now, using this list reduce dt
temperature_nolags <- spp_master_ztemp_seus_buoy[,..variable_names_reduced2]

#all variable names for a big collinarity matrix
variable_names_all <- variable_names_reduced[!grepl("mean", variable_names_reduced)]

#now, using this list reduce dt
temperature_withlags <- spp_master_ztemp_seus_buoy[,..variable_names_all]


```

Trait variables we need
```{r narrow down to trait variables that we need}
#columns to keep for collinearity matrix
trait_vars <- c("tl", "age.maturity", "length.max", "age.max")

#now, using this list reduce dt
traits <- spp_master_ztemp_seus_buoy.traits_scaled[,..trait_vars]

colnames(traits) <- c("trophic_level", "age_maturity", "length_max", "age_max")


```

Temp Correlation Matrix
```{r matrix all}
corr_full <- round(cor(temperature_withlags), 2)

ggcorrplot(corr_full, outline.color = "white", tl.cex = 1, tl.srt = 90, lab_size = 30)
ggsave(file = "temp_var_correlation_plot.jpg", dpi = 1000)

# Get the lower triangle
ggcorrplot(corr_full, type = "lower", outline.col = "white", tl.cex = 1, tl.srt = 90)
ggsave(file = "temp_var_correlation_plot_lower.jpg", dpi = 1000)

```


Correlation matrix small (no lags)
```{r  no lags}
corr_subset <- round(cor(temperature_nolags), 2)

ggcorrplot(corr_subset, outline.color = "white", tl.cex = 1, tl.srt = 90, lab_size = 30)
ggsave(file = "temp_var_correlation_plot_subset.jpg", dpi = 1000)

# Get the lower triangle
ggcorrplot(corr_subset,outline.col = "white", tl.cex = 7, lab =  T, lab_size = 2)
ggsave(file = "temp_var_correlation_plot_lower_subset.jpg", dpi = 1000)
```

Correlation matrix for traits
```{r  trait corr}
corr_subset_traits <- round(cor(traits, use = "complete.obs"), 2)

ggcorrplot(corr_subset_traits, outline.color = "white", lab = T)
ggsave(file = "trait_var_correlation_plot_subset.jpg", dpi = 1000)

```
