---
title: "Malin's Richness Temp Plot"
output: html_notebook
---

```{r setup}
library(data.table)
library(lme4)

load('comm_master.RData')
```

```{r plot}
trend <- function(y, x){ #function to extract coefficient
	return(coef(lm(y ~ x))[2])
}

scale <- function(x){ # function to scale by (ni-nmean)/sdn
	return((x-mean(x))/sd(x))
}


comm_master[reg=='neus', plot(year, reg_rich, type='o')]


# add trends and other vars
comm_master[,bt_trend:=trend(bt_ann,year), by=reg] #bottom temp change per year
comm_master[,bt_trend_abs:=abs(bt_trend)] #absolute value of bottom temp change per year
comm_master[,bt_trend_abs_sc:=scale(bt_trend_abs)] #scaled bottom temp change per year
comm_master[,year_sc:=scale(year)] #scaled year

# create summary data modeled richness and naive
trends <- comm_master[,.(rich=trend(reg_rich, year), rich_naive = trend(naive_rich, year), temp=trend(bt_ann,year)), by=reg] #calculate trend in richness per year and trend in annual temp per year

#modeled richness
setkey(comm_master, reg, year)
fd <- comm_master[,.(fyear=year[1:(.N-1)], richdiff=c(diff(reg_rich)), richdiff_naive = c(diff(naive_rich)), btdiff=c(diff(bt_ann))),by=reg]

#naive richness

# statistics
mod <- trends[,lm(rich ~ abs(temp))]
summary(mod)

mod2 <- fd[,lmer(richdiff ~ abs(btdiff) + (1|reg))]
summary(mod2)

mod3 <- comm_master[,lmer(reg_rich ~ year_sc + bt_trend_abs_sc + year_sc:bt_trend_abs_sc + (year_sc|reg))]
summary(mod3)
mod3b <- comm_master[,lmer(reg_rich ~ year_sc + bt_trend_abs_sc + (year_sc|reg))]
anova(mod3, mod3b)



# plot
quartz(width=5, height=4)
# pdf(width=5, height=4, file='figures/richnesstrend_vs_temperaturetrend.pdf')
par(las=1, mai=c(1,1,0.2, 0.2))
trends[,plot(abs(temp), rich, pch=16, cex=2, col='#1f78b4', ylab='Change in richness (spp/yr)', xlab='abs(Temperature trend) (°C/yr)')]
trends[,abline(mod, col='grey', lty=2)]

#dev.off()

# plot naive richness
#quartz(width=5, height=4)
# pdf(width=5, height=4, file='figures/richnesstrend_vs_temperaturetrend.pdf')
par(las=1, mai=c(1,1,0.2, 0.2))
trends[,plot(abs(temp), rich_naive, pch=16, cex=2, col='#1f78b4', ylab='Change in raw richness (spp/yr)', xlab='abs(Temperature trend) (°C/yr)')]
trends[,abline(mod, col='grey', lty=2)]

dev.off()

```

```{r Ryans temp patterns}
ryan_reduced <- comm_master[,.(reg, year, naive_rich, bt_ann)]
```



Difference between this and mine is that here, we plot temp trend VERSUS change in richness trend for each region, aka, we take AVERAGE temp trend and AVERAGE spp richness trend over the whole study period. For my plots, I had an independent value for each year: how much did temp change versus how much did species richness change?
