---
title: "Trawls by Year"
output: html_notebook
---

```{r setup}
library(data.table)
library(here)
library(ggplot2)

load(here::here("Data","InputTrawls", "trawl2.RData"))
```

```{r prep}
trawl2 <- trawl2[region != "NWFSC_WCAnn" & region != "DFO_SoGulf"] #surveys not used here

trawl2[,region := factor(region, labels = c("Aleutian Islands", "Eastern Bering Sea", "Gulf of Alaska", "West Coast US", "Newfoundland", "Scotian Shelf", "Northeast US","Southeast US" ,"Gulf of Mexico"))]

trawl2_latlon <- unique(trawl2[,.(lat,lon,stratum,s.reg,depth,year)])


trawl2.pivot <- data.table(table(trawl2_latlon$s.reg, trawl2_latlon$year))


#quick stats
min(trawl2.pivot[N != 0]$N)
max(trawl2.pivot[N != 0]$N)

View(trawl2.pivot)

#total?
sum(trawl2.pivot$N)
```

What about for only 6 annually sampled regions?
```{r}
trawl2_latlon_annual <- trawl2_latlon[!(s.reg %in% c("ai","goa","wctri"))]

trawl2.pivot.annual <- data.table(table(trawl2_latlon_annual$s.reg,trawl2_latlon_annual$year))

sum(trawl2.pivot.annual$N)
```


Average tows per year per region
```{r}
trawl2.pivot[,region_mean_tows:=mean(N),V1]

trawl2.pivot.u <- unique(trawl2.pivot[,.(V1, region_mean_tows)])
```

```{r bubble plot}
# Most basic bubble plot
bubble_year_region_trawls <- ggplot(trawl2.pivot, aes(x=as.numeric(V2), y=factor(V1, levels = rev(levels(factor(V1)))))) +
    geom_point(aes(size = ifelse(N == 0, NA, N))) +
#  geom_text(aes(label=N),nudge_x = -0.05, color =  "white", size = 0.5)  +
  labs(size = "Number of Tows", y = "Region", x = "Year") +
  theme_classic() +
  theme(legend.position = "top")

ggsave(bubble_year_region_trawls, height = 3, width = 8, unit = "in", filename = "bubble_plot_year_region_trawl.eps", path = here::here("figures","Supplemental"))
ggsave(bubble_year_region_trawls, height = 3, width = 8, unit = "in", filename = "bubble_plot_year_region_trawl.jpg", path = here::here("figures","Supplemental"))
```

