---
title: "Figure 4 Code Annual Observations Only"
output: html_notebook
---

Code to make Figure 4. 

```{r setup}
library(ggplot2)
library(data.table)
library(wesanderson)
library(cowplot)

RVI_gain_nolag <- readRDS(here::here("Model_results", "RVI_gain_nolag_annual_obs.rds"))
RVI_loss_nolag <- readRDS(here::here("Model_results", "RVI_loss_nolag_annual_obs.rds"))
```

Plot
```{r plot}
#plotting
pal <- wes_palette("GrandBudapest1", 8, type = "continuous")
colors <- c(pal[1], pal[2], "#FFFFFF", pal[3], pal[4], pal[5],"#FFFFFF", pal[6], pal[7], pal[8])

#gains
RVI_gain_plot <- ggplot(data = RVI_gain_nolag, aes(x=type, y = value, fill = variable)) +
  geom_bar(stat="identity", color = NA, size = 0, width = 0.8) +
  scale_x_discrete(breaks = c("Depth", "Transformation", "Metric"), labels = c("Depth", "Transformation", "Metric")) +
  labs(x = "Temperature Variables", y = "Relative Variable Importance") +
  theme_classic() +
  theme(text = element_text(size = 11.5), 
        legend.position = "right", 
        legend.title = element_blank(), 
        legend.spacing.x = unit(0.2, 'cm'),
        legend.justification = "center",
        aspect.ratio = (1),
        #, legend.position = "none"
        ) +
  guides(fill=guide_legend(ncol=1)) +
  scale_fill_manual(values = colors,
                    drop = F)

ggsave(here::here("figures","Supplemental","annual_sensitivity","Figure4a_annual.eps" ))

#loss
RVI_loss_plot <- ggplot(data = RVI_loss_nolag, aes(x=type, y = value, fill = variable)) +
  geom_bar(stat="identity", color = NA, size = 0, width = 0.8) +
  scale_x_discrete(breaks = c("Depth", "Transformation", "Metric"), labels = c("Depth", "Transformation", "Metric")) +
  labs(x = "Temperature Variables", y = "Relative Variable Importance") +
  theme_classic() +
  theme(text = element_text(size = 11.5), 
        legend.position = "right", 
        legend.title = element_blank(), 
        legend.spacing.x = unit(0.2, 'cm'),
        legend.justification = "center",
        aspect.ratio = (1),
        #, legend.position = "none"
        ) +
  guides(fill=guide_legend(ncol=1)) +
  scale_fill_manual(values = colors,
                    drop = F)

ggsave(here::here("figures","Supplemental","annual_sensitivity","Figure4b_annual.eps" ))



```

Arrange side by side
```{r arrange}
figure4 <- plot_grid(RVI_gain_plot + theme(legend.position = "none"), RVI_loss_plot + theme(legend.position = "none") + ylab(NULL), labels = c("b.", "c."), label_size = 12, align = "hv", axis = "bottom")

#pull legend
legend <- get_legend(RVI_gain_plot)

#add legend
figure4_wlegend <- plot_grid(figure4, legend, nrow = 1, rel_widths = c(8,1))

ggsave(here::here("figures","Supplemental","annual_sensitivity","Figure4_annual.eps"), height = 4, width = 8)
ggsave(here::here("figures","Supplemental","annual_sensitivity","Figure4_annual.jpg"), height = 4, width = 8)
```

Add in old figure 3
```{r adding in figure 3}
load(file = here::here("figures","Supplemental","annual_sensitivity","lags_over_time_annual_regs.RData"))

figure3_new_annual <- plot_grid(lags_over_time_annual_reg, figure4_wlegend, ncol = 1, nrow = 2, labels = c("a.","",""), vjust = 1)

ggsave(figure3_new_annual, path = here::here("figures","Supplemental","annual_sensitivity"), filename = "figure3_new_annual.eps", height = 6, width = 7.5, units = "in")
```

