---
title: "Regional statistics for Supplementary Table 1"
output: html_notebook
---
```{r setup}

library(data.table)
library(ggplot2)
library(lme4)

spp_master_ztemp_seus_buoy_scaled <- readRDS(here::here("Data","Spp_master","spp_master_ztemp_seus_buoy_scaled.rds"))
spp_master_ztemp_seus_buoy.traits_scaled <- readRDS(here::here("Data","Spp_master","spp_master_ztemp_seus_buoy.traits_scaled.rds"))

```

Link up with spp key to add phylum, order, family, etc.
```{r pull in spp, order, family, etc.}
spp_key <- fread(here::here("Data","Spp_master","spp_key.csv"))

spp_master_ztemp_seus_buoy_scaled <- spp_master_ztemp_seus_buoy_scaled[spp_key, on = "spp"]

spp_master_ztemp_seus_buoy.traits_scaled <- spp_master_ztemp_seus_buoy.traits_scaled[spp_key, on = "spp"]

#leave out sea turtle
spp_master_ztemp_seus_buoy_scaled <- spp_master_ztemp_seus_buoy_scaled[spp != "Caretta caretta",]

spp_master_ztemp_seus_buoy.traits_scaled <- spp_master_ztemp_seus_buoy.traits_scaled[spp != "Caretta caretta",]

#delete first year each region is sampled (because gains and losses are based on transitions between years, so we need 2 years of observations)

spp_master_ztemp_seus_buoy_scaled[,min_year := min(year),.(reg)]

spp_master_ztemp_seus_buoy_scaled <- spp_master_ztemp_seus_buoy_scaled[year != min_year]

spp_master_ztemp_seus_buoy.traits_scaled[,min_year := min(year),.(reg)]

spp_master_ztemp_seus_buoy.traits_scaled <- spp_master_ztemp_seus_buoy.traits_scaled[year != min_year]
```

Years per survey
```{r}
spp_master_ztemp_seus_buoy_scaled.uniqueyears <- unique(spp_master_ztemp_seus_buoy_scaled[,.(reg, year)])

table(spp_master_ztemp_seus_buoy_scaled.uniqueyears$reg)+1 #add one for first year
```


Regional statistics fish and inverts
```{r regional stats fish and inverts}
#count arrivals by region
arrivals <- spp_master_ztemp_seus_buoy_scaled[col == 1,.N,reg]
colnames(arrivals) <- c("reg","arrivals")

#count departures by region
departures <- spp_master_ztemp_seus_buoy_scaled[now_ext == 1,.N,reg]
colnames(departures) <- c("reg","departures")

#count observations by region
counts <- spp_master_ztemp_seus_buoy_scaled[,.N,reg]
colnames(counts) <- c("reg","counts")

region_summaries <- cbind(counts, arrivals[,arrivals], departures[,departures])
colnames(region_summaries) <- c("reg", "counts", "arrivals", "departures")

region_summaries[,arrivals_per := round((arrivals/counts)*100,2)][,departures_per := round((departures/counts)*100,2)]

region_summaries[,reg:= factor(reg, levels = c("ai","ebs","goa","gmex","newf","neus","shelf","sa","wctri"))]

region_summaries[,.(reg,counts, arrivals, arrivals_per, departures, departures_per)]

sum(region_summaries$arrivals)
sum(region_summaries$arrivals_per)
sum(region_summaries$departures)
sum(region_summaries$departures_per)
sum(region_summaries$arrivals)/sum(region_summaries$counts)
sum(region_summaries$departures)/sum(region_summaries$counts)
sum(region_summaries$counts)
```

Regional statistics fish only
```{r regional stats fish only}

#no sleeper
spp_master_ztemp_seus_buoy.traits_scaled_nosleeper <- spp_master_ztemp_seus_buoy.traits_scaled[spp != "Somniosus pacificus"]

#only observations with all three traits
arrival.reduced_annual_obs <- spp_master_ztemp_seus_buoy.traits_scaled_nosleeper[complete.cases(spp_master_ztemp_seus_buoy.traits_scaled_nosleeper[ , .(age.max_ocean_scaled, age.maturity_ocean_scaled, length.max_ocean_scaled, tl_ocean_scaled)]),]

#order by region
setkey(arrival.reduced_annual_obs, reg)
#count arrivals by region
arrivals_fish <- arrival.reduced_annual_obs[col == 1,.N,reg]
colnames(arrivals_fish) <- c("reg","arrivals")

#count departures by region
departures_fish <- arrival.reduced_annual_obs[now_ext == 1,.N,reg]
colnames(departures_fish) <- c("reg","departures")

#count observations by region
counts_fish <- arrival.reduced_annual_obs[,.N,reg]
colnames(counts_fish) <- c("reg","counts")

region_summaries_fish <- cbind(counts_fish, arrivals_fish[,arrivals], departures_fish[,departures])
colnames(region_summaries_fish) <- c("reg", "counts", "arrivals", "departures")

region_summaries_fish[,arrivals_per := round((arrivals/counts)*100,2)][,departures_per := round((departures/counts)*100,2)][,reg2 := reg]

region_summaries_fish

sum(region_summaries_fish$counts)
sum(region_summaries_fish$arrivals)/sum(region_summaries_fish$counts)
sum(region_summaries_fish$departures)/sum(region_summaries_fish$counts)
```

