---
title: "Figure 4 Code"
output: html_notebook
---

Code to make Figure 4. 

```{r setup}
library(ggplot2)
library(data.table)
library(wesanderson)
library(cowplot)

RVI_arrival_nolag <- readRDS(here("Model_results", "RVI_arrival_nolag.rds"))
RVI_departure_nolag <- readRDS(here("Model_results", "RVI_departure_nolag.rds"))
```

Plot
```{r plot}
#arrivals
RVI_arrival_plot <- ggplot(data = RVI_arrival_nolag, aes(x=type, y = value, fill = variable)) +
  geom_bar(stat="identity", color = NA, size = 0, width = 0.8) +
  scale_x_discrete(breaks = c("Depth", "Transformation", "Metric"), labels = c("Depth", "Transformation", "Metric")) +
  labs(x = "Temperature Variables", y = "Relative Variable Importance") +
  theme_classic() +
  theme(text = element_text(size = 11.5), 
        legend.position = "right", 
        legend.title = element_blank(), 
        legend.spacing.x = unit(0.2, 'cm'),
        legend.justification = "center",
        aspect.ratio = (1),
        #, legend.position = "none"
        ) +
  guides(fill=guide_legend(ncol=1)) +
  scale_fill_manual(values = colors,
                    drop = F)

ggsave(here("figures","Figure3-3_4_merge","figure4","Figure4a.eps" ))

#departure
RVI_departure_plot <- ggplot(data = RVI_departure_nolag, aes(x=type, y = value, fill = variable)) +
  geom_bar(stat="identity", color = NA, size = 0, width = 0.8) +
  scale_x_discrete(breaks = c("Depth", "Transformation", "Metric"), labels = c("Depth", "Transformation", "Metric")) +
  labs(x = "Temperature Variables", y = "Relative Variable Importance") +
  theme_classic() +
  theme(text = element_text(size = 11.5), 
        legend.position = "right", 
        legend.title = element_blank(), 
        legend.spacing.x = unit(0.2, 'cm'),
        legend.justification = "center",
        aspect.ratio = (1),
        #, legend.position = "none"
        ) +
  guides(fill=guide_legend(ncol=1)) +
  scale_fill_manual(values = colors,
                    drop = F)

ggsave(here("figures","Figure3-3_4_merge","figure4","Figure4b.eps" ))



```

Arrange side by side
```{r arrange}
figure4 <- plot_grid(RVI_arrival_plot + theme(legend.position = "none"), RVI_departure_plot + theme(legend.position = "none") + ylab(NULL), labels = c("b.", "c."), label_size = 12, align = "hv", axis = "bottom")

#pull legend
legend <- get_legend(RVI_arrival_plot)

#add legend
figure4_wlegend <- plot_grid(figure4, legend, nrow = 1, rel_widths = c(8,1))

ggsave(here("figures","Figure3-3_4_merge","figure4","Figure4.eps"), height = 4, width = 8)
ggsave(here("figures","Figure3-3_4_merge","figure4","Figure4.jpg"), height = 4, width = 8)
```

Add in old figure 3
```{r adding in figure 3}
load(here("figures","Figure3-3_4_merge","figure3","lags_over_time.RData"))

figure3_new <- plot_grid(lags_over_time, figure4_wlegend, ncol = 1, nrow = 2, labels = c("a.","",""))

ggsave(figure3_new, path = here("figures","Figure3-3_4_merge"), filename = "figure3_new.eps", height = 6, width = 7.5, units = "in")
```

